---
fileVersion: v1
serverName: Chat
protoFile: "/GrpcWpfSample.Common/chat.proto"
calls:
- method: Subscribe
  response:
    streamFromJsonFile: "/res.json"
    status: OK
- method: Write
  request:
    body:
      matchesJsonFile: "/req.json"
  response:
    status: OK
- method: Write
  request:
    body:     
      matchesJPath: "$[?(@.content=='hi mate')].content"
  response:
    status: OK
- method: Write
  request:
    body:     
      content:
        contains: "Hi!"
  response:
    status: OK
- method: Write  
  response:
    status: NOT_FOUND
