---
fileVersion: v1
serverName: ChatWithFeature
protoFile: "/GrpcWpfSample.Common/chat.proto"
calls:
- method: Subscribe
  response:
    streamFromJsonFile: "/res.json"
    status: OK
- method: Write
  request:
    body:
      matchesJsonFile: "/req.json"
  response:
    status: OK
